[CmdletBinding()]
param(
  [Parameter(Mandatory = $false)]
  [string]$SecretsPath = "ansible/vars/secrets.yml"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function New-RandomHex([int]$Bytes) {
  $buffer = New-Object byte[] $Bytes
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buffer)
  return ($buffer | ForEach-Object { $_.ToString('x2') }) -join ''
}

$fullPath = Join-Path (Get-Location) $SecretsPath
$dir = Split-Path -Parent $fullPath
if (-not (Test-Path $dir)) {
  New-Item -ItemType Directory -Path $dir | Out-Null
}

if (Test-Path $fullPath) {
  Write-Host "Secrets file already exists: $SecretsPath" -ForegroundColor Yellow
  Write-Host "Refusing to overwrite." -ForegroundColor Yellow
  exit 0
}

$n8nEncryptionKey = New-RandomHex -Bytes 32
$postgresPassword = New-RandomHex -Bytes 24
$basicAuthPassword = New-RandomHex -Bytes 18

$content = @"
# Generated by scripts/new-secrets.ps1
# Do not commit this file.

n8n_encryption_key: "$n8nEncryptionKey"
postgres_password: "$postgresPassword"

# If you enable N8N basic auth in env.j2, set these too
n8n_basic_auth_user: "admin"
# Change if you want a human-memorable value
n8n_basic_auth_password: "$basicAuthPassword"
"@

$content | Out-File -FilePath $fullPath -Encoding utf8 -NoNewline
Write-Host "Wrote secrets to: $SecretsPath" -ForegroundColor Green
